### ISSUE TITLE
'rust_backend' not found

### ISSUE THREAD

**Issue by wapordev** [Sin-tel/tessera#1]
I'm very interested in trying new music software, as a lot of available are not for me.

I'm not able to run this yet though, as I get the following error:
![image](https://github.com/Sin-tel/tessera/assets/48777791/381ed3de-f86c-47c0-94a1-e8d0d9b2575c)

I also had to update the cpal dependancy as the current one could not compile on my machine.

**Comment by wapordev** [comment]
Actually, looking through the error myself a bit, seems like it expects a debug build from that file path? Doing so gives me a different result:
![image](https://github.com/Sin-tel/tessera/assets/48777791/4ec06a55-c170-4cf3-af28-c4eab685bd5e)
got the program running by replacing "settings.audio.default_host" with string "default" in main.lua/audioSetup(). Seems like you are passing in an unset mutable value, like how settings.audio.default_device is, but this one is expected to be already set to "default" or a device name? Idk it works now though

**Comment by Sin-tel** [comment]
There is a global 'release' flag on top of main.lua that determines whether it loads the debug or release build.

Second issue I have no idea what's happening, since those variables should always be set in the handler: 
https://github.com/Sin-tel/tessera/blob/master/lua/settings_handler.lua#L24-L25 
Doing the audiosetup correctly is quite finicky to be honest, I really need to get it more robust and do some kind of device polling. 

Thanks for testing it out! I'm actually surprised you managed to get it running seeing that it's not anywhere near production right now.

**Comment by Sin-tel** [comment]
I added some instructions in dcafd8d25bfafa17b70f9cac223f603626d968b2 which should help people with their setup.

**Comment by wapordev** [comment]
> Thanks for testing it out! I'm actually surprised you managed to get it running seeing that it's not anywhere near production right now.

you're welcome! I love seeing new ways of making electronic audio, it was fun to fiddle around with it.
